### ISSUE TITLE
Error on Colab

### ISSUE THREAD

**Issue by pimonteiro** [JonasStankevicius/ConvPoint_Keras#1]
Hello! I'm trying to run your code on Google Colab but keep having the following error:

Traceback (most recent call last):
  File "ConvPoint.py", line 1846, in <module>
    from KDTree import KDTreeLayer, KDTreeSampleLayer
  File "/content/ConvPoint_Keras/KDTree.py", line 8, in <module>
    import knn.lib.python.nearest_neighbors as nearest_neighbors
ModuleNotFoundError: No module named 'knn.lib'

All I did was clone your repos, install some of the packages I noticed weren't previously installed and run the ConvPoint.py

**Comment by JonasStankevicius** [comment]
Hi!

You need to build knn library manually, to do that run knn/setup.py
```
%cd ./knn
!python setup.py install --home="."
```
Actually, I was also using a windows10 machine, run build_knn.bat in that case.

Keep in mind you will also need to preprocess data.
dataTool.py PreprocessDatasetToVoxels method should help you but there will be more effort required from your side because this code as mentioned is not cleaned up.

My recommendation would be to use only the Keras model which is created in method ConvPoint.py CreateModel.
You can always reference the original ConvPoint repo for more clear code.
